.MODEL SMALL


.STACK 100H


.DATA
CR EQU 0DH
LF EQU 0AH
X DB ?
Y DB ?
Z DB ?

MSG1 DB CR,LF,'X-2*Y= $'
MSG2 DB CR,LF,'25-(X+Y)= $'
MSG3 DB CR,LF,'2X-3Y= $'
MSG4 DB CR,LF,'Y-X+1= $'

MSGX DB CR,LF,'ENTER VALUE OF X: $'
MSGY DB CR,LF,'ENTER VALUE OF Y: $'

.CODE

MAIN PROC
	;DATA SEGMENT INITIALIZATION
    MOV AX, @DATA
    MOV DS, AX


    MOV AH , 01H ; AH <- 01 ,MODE TO TAKE CHARACTER AS ASCII WHEN INT 21H IS CALLED
    INT 21H ; CALLING INTURRAPT TO TAKE INPUT , ASCII VALUE WILL BE AT #AL


    MOV AH, 02H ; AG <- 02 , MODE TO PRINT CHARACTER FROM DL
    MOV DL, 'A'
    INT 21H

    LEA DX , MSG1
    MOV AH,09H ; MOD TO PRINT STRING ENDDED WITH '$' , STRING LOCATION GIVEN IN DX
    INT 21H ; PRINT



    ;Return 0
    MOV AH, 4CH
    INT 21H


MAIN ENDP
    END MAIN
