#line 2 "analyzer.cpp"

#line 4 "analyzer.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 48
#define YY_END_OF_BUFFER 49
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[162] =
    {   0,
        6,    6,   49,   47,    2,    1,    2,   23,   45,   34,
       47,   43,   24,   25,   33,   30,   33,   47,   34,    5,
       31,   36,   22,   37,   37,   28,   29,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   26,   47,   27,
        2,    1,   36,   45,   38,    0,   32,   43,    0,   43,
       44,   43,   35,   39,    6,   46,    3,    0,    5,   40,
       40,   37,    0,    6,   37,   37,   37,   12,   37,   37,
       37,    8,   37,   37,   37,   37,   37,    0,   43,    0,
       43,    7,    0,   43,   43,   39,   46,    0,    3,    3,
       40,    6,    6,    0,    6,   37,   37,   37,   37,   37,

       37,   37,   37,   10,   14,   37,   37,   37,   37,   43,
        0,   42,   43,    0,   42,   42,    7,    7,    4,    0,
        6,   40,   40,    6,   40,   41,    0,   37,   37,   21,
       15,   37,    9,   37,   37,   37,   18,   37,   42,   42,
       40,    0,   41,   37,   37,   13,   37,   16,   37,   37,
       11,   40,   40,    0,   41,   41,    0,   17,   19,   20,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,    8,   22,   23,
       24,   23,    8,    8,   25,   25,   25,   25,   26,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       27,   28,   29,    8,   30,    8,   31,   32,   33,   34,

       35,   36,   25,   37,   38,   25,   39,   40,   25,   41,
       42,   25,   25,   43,   44,   45,   46,   47,   48,   25,
       25,   25,   49,   50,   51,    8,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[52] =
    {   0,
        1,    1,    2,    2,    1,    1,    1,    1,    1,    1,
        3,    1,    1,    1,    1,    1,    1,    4,    1,    5,
        5,    1,    1,    1,    5,    5,    1,    1,    1,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    1,    1,
        1
    } ;

static const flex_int16_t yy_base[175] =
    {   0,
        0,    0,  364,  365,   50,   54,   58,  339,   57,  365,
      352,   64,  365,  365,  346,  365,  343,   50,   53,   56,
      365,  335,  334,    0,   63,  365,  365,  314,   42,  314,
      315,   46,   53,  319,  305,  310,  314,  365,  300,  365,
       93,   97,  365,   80,  365,   87,  365,   76,   82,   98,
      365,  122,  365,   93,   97,  335,  320,  101,  110,    0,
      117,    0,   85,  123,  312,  302,  309,  289,  284,  276,
      271,    0,  268,  261,  263,  258,  256,  287,  124,   96,
      134,  365,  129,  150,  155,  150,  267,  260,  247,  144,
        0,  155,  159,  166,  170,    0,  177,  240,  233,  220,

      227,  219,  221,    0,    0,  200,  189,  198,  182,  184,
      171,  365,  195,  173,  197,  182,  365,  198,  365,  213,
      193,    0,  200,  209,  216,  218,  184,  222,  168,    0,
        0,  134,    0,  119,  116,  123,    0,  116,  213,  217,
      229,  236,  240,  244,  252,    0,  111,    0,   84,   83,
        0,  256,  263,  265,  267,  271,  278,    0,    0,    0,
      365,  299,  304,  306,  111,  311,  316,  321,  326,  107,
      328,  333,  338,  340
    } ;

static const flex_int16_t yy_def[175] =
    {   0,
      161,    1,  161,  161,  161,  161,  161,  161,  162,  161,
      161,  163,  161,  161,  161,  161,  161,  161,  161,  164,
      161,  161,  161,  165,  165,  161,  161,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  161,  161,  161,
      161,  161,  161,  162,  161,  162,  161,  166,  167,  166,
      161,  166,  161,  161,  164,  168,  169,  161,  164,  170,
      170,  165,  161,  171,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  161,  172,  173,
      172,  161,  173,  172,  172,  161,  168,  168,  169,  169,
      170,  174,  164,  161,  171,  165,  165,  165,  165,  165,

      165,  165,  165,  165,  165,  165,  165,  165,  165,  172,
      173,  161,  172,  173,  172,  173,  161,  172,  161,  161,
      174,  170,  170,  164,  170,  161,  161,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  172,  173,
      170,  161,  161,  165,  165,  165,  165,  165,  165,  165,
      165,  170,  170,  161,  161,  161,  161,  165,  165,  165,
        0,  161,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  161,  161,  161
    } ;

static const flex_int16_t yy_nxt[417] =
    {   0,
        4,    5,    6,    7,    5,    8,    9,    4,   10,   11,
       12,   13,   14,   10,   15,   16,   17,   18,   19,   20,
       20,   21,   22,   23,   24,   25,   26,    4,   27,   24,
       24,   28,   29,   30,   31,   32,   24,   33,   24,   24,
       24,   24,   34,   35,   24,   24,   36,   37,   38,   39,
       40,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       42,   41,   41,   45,   48,   48,   56,   54,   49,   55,
       55,   57,   66,   58,   51,   59,   59,   63,   67,   63,
       80,   61,   64,   64,   46,   70,   45,   71,   72,   44,
       78,   52,   82,   73,   41,   41,   41,   41,   41,   41,

       41,   41,   80,   81,   93,   93,  112,   46,   82,   83,
       54,   91,   86,   86,   54,   62,   55,   55,   54,  160,
       55,   55,   61,  114,  159,   81,   80,   58,  111,   59,
       59,   63,   50,   63,  112,   61,   92,   92,  111,  116,
       94,   84,   95,   95,  115,  158,   89,  120,   97,   85,
      151,  113,   84,   84,  111,  150,  114,   84,  149,  111,
      117,  113,   84,  148,   84,  118,   84,   54,   84,   86,
       86,   90,   94,  147,  121,  121,   94,  113,  124,  124,
      123,  112,  113,  140,  125,  126,  126,   94,  111,   95,
       95,  127,  112,  127,  112,   97,  128,  128,  114,  111,

      114,  111,  111,  143,  143,  139,  146,  112,  112,  114,
       94,  113,  121,  121,  127,   89,  127,  111,  123,  141,
      141,  138,  113,  112,  113,  113,   94,  112,  124,  124,
      127,  137,  127,  136,  125,  141,  141,  126,  126,   94,
      113,  144,  144,  142,  114,  135,   94,  145,  152,  152,
      154,  134,  154,  133,  153,  155,  155,   94,  132,  156,
      156,   94,  131,  144,  144,  157,  127,  130,  127,  145,
      129,  128,  128,   94,   90,  152,  152,  127,  119,  127,
       88,  153,  141,  141,  155,  155,  155,  155,   94,   44,
      156,  156,  127,  109,  127,  108,  157,  143,  143,   44,

      107,   44,   44,   44,   50,  106,   50,   50,   50,   60,
       60,   79,  105,  104,   79,   79,   80,  103,   80,   80,
       80,   87,   87,   87,   87,   87,   89,  102,   89,   89,
       89,   96,   96,  110,  101,  110,  110,  110,  111,  100,
      111,  111,  111,  122,  122,   99,   98,   90,   88,   47,
       77,   76,   75,   74,   69,   68,   65,   43,   43,   53,
       53,   47,   43,  161,    3,  161,  161,  161,  161,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,

      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  161,  161,  161,  161,  161
    } ;

static const flex_int16_t yy_chk[417] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    5,    5,    5,    6,    6,    6,    6,    7,
        7,    7,    7,    9,   12,   12,   19,   18,   12,   18,
       18,   19,   29,   20,   12,   20,   20,   25,   29,   25,
       48,   20,   25,   25,    9,   32,   44,   32,   33,   46,
       46,   12,   49,   33,   41,   41,   41,   41,   42,   42,

       42,   42,   50,   48,   63,   63,   80,   44,   50,   49,
       54,  170,   54,   54,   55,  165,   55,   55,   58,  150,
       58,   58,   55,   80,  149,   50,   52,   59,   79,   59,
       59,   61,   52,   61,   79,   59,   61,   61,   81,   83,
       64,   52,   64,   64,   81,  147,   90,   90,   64,   52,
      138,   79,   52,   52,   84,  136,   83,   52,  135,   85,
       84,   81,   52,  134,   52,   85,   52,   86,   52,   86,
       86,   90,   92,  132,   92,   92,   93,   84,   93,   93,
       92,  111,   85,  114,   93,   94,   94,   95,  110,   95,
       95,   97,  116,   97,  110,   95,   97,   97,  111,  113,

      114,  115,  118,  127,  127,  113,  129,  115,  118,  116,
      121,  110,  121,  121,  123,  120,  123,  139,  121,  123,
      123,  109,  113,  139,  115,  118,  124,  140,  124,  124,
      125,  108,  125,  107,  124,  125,  125,  126,  126,  128,
      139,  128,  128,  126,  140,  106,  141,  128,  141,  141,
      142,  103,  142,  102,  141,  142,  142,  143,  101,  143,
      143,  144,  100,  144,  144,  143,  145,   99,  145,  144,
       98,  145,  145,  152,   89,  152,  152,  153,   88,  153,
       87,  152,  153,  153,  154,  154,  155,  155,  156,   78,
      156,  156,  157,   77,  157,   76,  156,  157,  157,  162,

       75,  162,  162,  162,  163,   74,  163,  163,  163,  164,
      164,  166,   73,   71,  166,  166,  167,   70,  167,  167,
      167,  168,  168,  168,  168,  168,  169,   69,  169,  169,
      169,  171,  171,  172,   68,  172,  172,  172,  173,   67,
      173,  173,  173,  174,  174,   66,   65,   57,   56,   39,
       37,   36,   35,   34,   31,   30,   28,   23,   22,   17,
       15,   11,    8,    3,  161,  161,  161,  161,  161,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,

      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  161,  161,  161,  161,  161
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[49] =
    {   0,
1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 
    0, 0, 0, 0, 0, 1, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "1705003.l"
#line 3 "1705003.l"

#include "SymbolTable.h"

#include<bits/stdc++.h>
using namespace std;
#define DBG(x) cerr << (__LINE__) << " : " << (#x) << " -> " << (x) << "\n";

#define NL cout<<endl;

SymbolTable<string> * symboltable;

void printTokenAscii(char * s)
{
	while(*s)
		{
			cout<<(int)(*s)<<" ";
			s++;
		}
}

string get_row_char(string chs)
{
	if(chs == "\\n")
		chs = '\n';
	else if(chs == "\\a")
		chs = '\a';
	else if(chs == "\\f")
		chs = '\f';
	else if(chs == "\\r")
		chs = '\r';
	else if(chs == "\\b")
		chs = '\b';
	else if(chs == "\\v")
		chs = '\v';
	else if(chs == "\\0")
		chs = '\0';
	else if(chs == "\\t")
		chs = '\t';
	else if(chs == "\\\\")
		chs = '\\';
	else if(chs == "\\\'")
		chs = '\'';
	else if (chs == "\\\"")
		chs = '"';
	else if(chs.size() == 2 and chs[0] == '\\')
		chs = chs[1];

	// assert(chs.size() == 1);
	return chs;
}

string get_row_string(string s)
{
	/*
		backslash must followed by and chararcter
	*/
	string ret ="";
	for(int i=0;i<s.size();i++)
	{
		if(s[i] == '\\')
		{

			if(s[i+1] == '\n')
			{
				i++;
			}
			else if(i+2<s.size() and s[i+1] == '\r' and s[i+2] == '\n')
			{
				i+=2;
			}
			else 
			{
				ret+=get_row_char(s.substr(i,2));
				i++;
			}
		}
		else ret+=s[i];
	}
	return ret;
}

int get_lineno()
{
	string symbol = yytext;
	int ret =  yylineno;
	for(char c:symbol)
		ret-=c=='\n';
	return ret;
}

void processsToken(string token , string attr)
{
	cout<<"<"<<token;
	if(attr!="")
		cout<<", "<<attr;
	cout<<"> ";
}

int error_count = 0;

void processError(int line_number, string text, string reason)
{
	error_count++;
	cerr<<"Error at line no "<<line_number<<": "<<reason<<" "<<text<<"\n";
}

void insertSymbol(string key , string value)
{
	if(symboltable->insert(key , value))
		symboltable->printNonEmptyBuckets(cerr);
}

#line 732 "analyzer.cpp"
#line 117 "1705003.l"
	// to comment in this section : TAB\\ or TAB/*
	// line comment = // anything except new line  + continous line\
						= anychar except \r + continous line
	//block comment = /* ( anything except */  \
						=  anything except * at begining +\
						 anything with * at begining \
						 followed by anythinh except / )  */
	//float  = 3.14159, 3.14159E-10, .314159 and 314159E10
	//'\n','\t','\\','\'','\a','\f','\r','\b','\v'and'\0'
	// or 'a' , 'z'
	// can't contain \r\n anywhere except continuous line
	// can't  end with \" 
	// can't contain single "
	// can contain continuous line
	// if escape char then any char must follow
	// so inside string  = ( not escape + not " + not \n + not \r) or (escape + anychar) or continuous line
	// + , - ADDOP
	//*, /, % MULOP
	//++, - - INCOP
	//<, <=, >, >=, ==, != RELOP
	//&&, || LOGICOP
	// single ' followed by enything except single ' or space newline
	// just same regx except last " part
	// same regx  as block comment without last */
	// line comment cannot be unterminated
#line 759 "analyzer.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 179 "1705003.l"


#line 979 "analyzer.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 162 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 365 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 181 "1705003.l"
{
				//cout<<"New Line paise";
				//printTokenAscii(yytext);
				//cout<<" \n";
				//NL;
			}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 187 "1705003.l"
{
					//cout<<"white spaces\n";
				}
	YY_BREAK
/*{CONTINUOUS_LINE}	{
				cout<<"CONTINUOUS_LINE paise";
				//printTokenAscii(yytext);
				//cout<<" \n";
				NL;
			}
	*/
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 198 "1705003.l"
{
					
					cerr<<"Line no "<< get_lineno() <<": Token <COMMENT> Lexeme "<<yytext<<" found\n";
				}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 202 "1705003.l"
{
					cerr<<"Line no "<< get_lineno() <<": Token <COMMENT> Lexeme "<<yytext<<" found\n";;
				}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 206 "1705003.l"
{
		string symbol = string(yytext);
		processsToken("CONST_INT" , symbol);
		cerr<<"Line no "<< get_lineno() <<": Token <CONST_INT> Lexeme "<<symbol<<" found\n";
		insertSymbol(symbol ,"CONST_INT" );
	}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 213 "1705003.l"
{
		string symbol = string(yytext);
		processsToken("CONST_FLOAT" ,symbol );
		cerr<<"Line no "<< get_lineno() <<": Token <CONST_FLOAT> Lexeme "<<symbol<<" found\n";
		insertSymbol(symbol ,"CONST_FLOAT" );
	}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 219 "1705003.l"
{
					string symbol = string(yytext);
					string ascii_symbol = symbol;
					if(ascii_symbol[0] == '\'')
						ascii_symbol = ascii_symbol.substr(1);
					if(ascii_symbol.back() == '\'')
						ascii_symbol.pop_back();

					/* '\n','\t','\\',
			'\'','\a','\f','\r','\b','\v'and'\0'. */
					
					ascii_symbol = get_row_char(ascii_symbol);

					processsToken("CONST_CHAR" , ascii_symbol);
					cerr<<"Line no "<< get_lineno() <<": Token <CONST_CHAR> Lexeme "<<symbol<<"found --> <CHAR_CONST, "<<ascii_symbol<<"> \n";
					insertSymbol(symbol ,"CONST_CHAR" );
				}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 237 "1705003.l"
{
                processsToken("IF","");
                cerr<<"Line no "<< get_lineno() <<": Token <IF> Lexeme "<<yytext<<" found\n";  
        }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 241 "1705003.l"
{
                processsToken("ELSE","");
                cerr<<"Line no "<< get_lineno() <<": Token <ELSE> Lexeme "<<yytext<<" found\n";
        }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 245 "1705003.l"
{
                processsToken("FOR","");
                cerr<<"Line no "<< get_lineno() <<": Token <FOR> Lexeme "<<yytext<<" found\n";
        }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 249 "1705003.l"
{
                processsToken("WHILE","");
                cerr<<"Line no "<< get_lineno() <<": Token <WHILE> Lexeme "<<yytext<<" found\n";
        }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 253 "1705003.l"
{
                processsToken("DO","");
                cerr<<"Line no "<< get_lineno() <<": Token <DO> Lexeme "<<yytext<<" found\n";
        }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 257 "1705003.l"
{
                processsToken("BREAK","");
                cerr<<"Line no "<< get_lineno() <<": Token <BREAK> Lexeme "<<yytext<<" found\n";
        }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 261 "1705003.l"
{
                processsToken("INT","");
                cerr<<"Line no "<< get_lineno() <<": Token <INT> Lexeme "<<yytext<<" found\n";
        }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 265 "1705003.l"
{
                processsToken("CHAR","");
                cerr<<"Line no "<< get_lineno() <<": Token <CHAR> Lexeme "<<yytext<<" found\n";
        }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 269 "1705003.l"
{
                processsToken("FLOAT","");
                cerr<<"Line no "<< get_lineno() <<": Token <FLOAT> Lexeme "<<yytext<<" found\n";
        }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 273 "1705003.l"
{
                processsToken("DOUBLE","");
                cerr<<"Line no "<< get_lineno() <<": Token <DOUBLE> Lexeme "<<yytext<<" found\n";
        }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 277 "1705003.l"
{
                processsToken("VOID","");
                cerr<<"Line no "<< get_lineno() <<": Token <VOID> Lexeme "<<yytext<<" found\n";
        }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 281 "1705003.l"
{
                processsToken("RETURN","");
                cerr<<"Line no "<< get_lineno() <<": Token <RETURN> Lexeme "<<yytext<<" found\n";
        }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 285 "1705003.l"
{
                processsToken("SWITCH","");
                cerr<<"Line no "<< get_lineno() <<": Token <SWITCH> Lexeme "<<yytext<<" found\n";
        }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 289 "1705003.l"
{
                processsToken("CASE","");
                cerr<<"Line no "<< get_lineno() <<": Token <CASE> Lexeme "<<yytext<<" found\n";
        }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 293 "1705003.l"
{
                processsToken("ASSIGNOP",string(yytext));
                cerr<<"Line no "<< get_lineno() <<": Token <ASSIGNOP> Lexeme "<<yytext<<" found\n";
        }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 297 "1705003.l"
{
                processsToken("NOT",string(yytext));
                cerr<<"Line no "<< get_lineno() <<": Token <NOT> Lexeme "<<yytext<<" found\n";
        }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 301 "1705003.l"
{
                processsToken("LPAREN",string(yytext));
                cerr<<"Line no "<< get_lineno() <<": Token <LPAREN> Lexeme "<<yytext<<" found\n";
        }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 305 "1705003.l"
{
                processsToken("RPAREN",string(yytext));
                cerr<<"Line no "<< get_lineno() <<": Token <RPAREN> Lexeme "<<yytext<<" found\n";
        }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 309 "1705003.l"
{
                processsToken("LCURL",string(yytext));
				symboltable->enterScope();
                cerr<<"Line no "<< get_lineno() <<": Token <LCURL> Lexeme "<<yytext<<" found\n";
        }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 314 "1705003.l"
{
                processsToken("RCURL",string(yytext));
				symboltable->exitScope();
                cerr<<"Line no "<< get_lineno() <<": Token <RCURL> Lexeme "<<yytext<<" found\n";
        }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 319 "1705003.l"
{
                processsToken("LTHIRD",string(yytext));
                cerr<<"Line no "<< get_lineno() <<": Token <LTHIRD> Lexeme "<<yytext<<" found\n";
        }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 323 "1705003.l"
{
                processsToken("RTHIRD",string(yytext));
                cerr<<"Line no "<< get_lineno() <<": Token <RTHIRD> Lexeme "<<yytext<<" found\n";
        }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 327 "1705003.l"
{
                processsToken("COMMA",string(yytext));
                cerr<<"Line no "<< get_lineno() <<": Token <COMMA> Lexeme "<<yytext<<" found\n";
        }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 331 "1705003.l"
{
                processsToken("SEMICOLON",string(yytext));
                cerr<<"Line no "<< get_lineno() <<": Token <SEMICOLON> Lexeme "<<yytext<<" found\n";
        }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 335 "1705003.l"
{
				processsToken("LOGICOP",string(yytext));
                cerr<<"Line no "<< get_lineno() <<": Token <LOGICOP> Lexeme "<<yytext<<" found\n";
        }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 339 "1705003.l"
{
				processsToken("ADDOP",string(yytext));
                cerr<<"Line no "<< get_lineno() <<": Token <ADDOP> Lexeme "<<yytext<<" found\n";
			}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 343 "1705003.l"
{
				processsToken("MULOP",string(yytext));
                cerr<<"Line no "<< get_lineno() <<": Token <MULOP> Lexeme "<<yytext<<" found\n";
			}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 347 "1705003.l"
{
				processsToken("INCOP",string(yytext));
                cerr<<"Line no "<< get_lineno() <<": Token <INCOP> Lexeme "<<yytext<<" found\n";
			}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 351 "1705003.l"
{
				processsToken("RELOP",string(yytext));
                cerr<<"Line no "<< get_lineno() <<": Token <RELOP> Lexeme "<<yytext<<" found\n";
			}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 357 "1705003.l"
{ 
					string symbol = string(yytext);
					processsToken("ID" , symbol);

					cerr<<"Line no "<< get_lineno() <<": Token <ID> Lexeme "<<symbol<<" found\n";
					insertSymbol(symbol , "ID");
					// if(symboltable->insert(symbl,"ID"))
					// 	symboltable->printNonEmpotyBuckets(cerr);
				}
	YY_BREAK
case 38:
/* rule 38 can match eol */
YY_RULE_SETUP
#line 367 "1705003.l"
{ 
					//cerr<<yytext<<"\n";
					string symbol = string(yytext);
					//cout<<"<STRING, "<<symbol<<">";
					string row_symbol = get_row_string(symbol);
					
					processsToken("STRING" , row_symbol);

					cerr<<"Line no "<< get_lineno() <<": Token <STRING> Lexeme "<<symbol<<" found";
					cerr<<" --> <STRING, "<<row_symbol<<">\n";

				}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 380 "1705003.l"
{
								processError( get_lineno()  , yytext , "Too many decimal points");
							}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 383 "1705003.l"
{
									processError( get_lineno()  , yytext , "Invalid prefix on ID or invalid suffix on Number");
								}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 386 "1705003.l"
{
							processError( get_lineno()  , yytext , "Ill formed number");
						}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 389 "1705003.l"
{
						processError( get_lineno()  , yytext , "Multi character constant error");
					}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 392 "1705003.l"
{
							processError( get_lineno()  , yytext , "Unterminated character");
						}	
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 395 "1705003.l"
{
						processError( get_lineno()  , yytext , "Empty character constant error");
					}	
	YY_BREAK
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP
#line 398 "1705003.l"
{
								processError( get_lineno()  , yytext , "Unterminated String");
							}
	YY_BREAK
case 46:
/* rule 46 can match eol */
YY_RULE_SETUP
#line 401 "1705003.l"
{
			processError( get_lineno()  ,yytext , "Unterminated Comment");
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 404 "1705003.l"
{
		processError( get_lineno()  , yytext , "Unrecognized character" );
	}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 407 "1705003.l"
ECHO;
	YY_BREAK
#line 1464 "analyzer.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 162 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 162 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 161);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 407 "1705003.l"


int main(int argc,char *argv[]){
	
	if(argc<3){
		printf("Please provide input file name , log_file_name , [output_file_name] and try again\n");
		return 0;
	}
	
	FILE *fin=fopen(argv[1],"r");
	if(fin==NULL){
		printf("Cannot open specified file\n");
		return 0;
	}

	freopen(argv[2] , "w+" , stderr);
	if(3 < argc)
		freopen(argv[3] , "w+" , stdout);

	ScopeTable<string>::setTotalBucket(7);
	symboltable = new SymbolTable<string>();

	yylineno  = 1;
	yyin= fin;
	yylex();
	
	symboltable->printNonEmptyBuckets(cerr);
	cerr<<"Total lines: "<< yylineno <<"\n";
	cerr<<"Total errors: "<<error_count<<"\n";

	fclose(yyin);

	delete  symboltable;

	return 0;
}

